name: conserFAIRy
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - annotated-doc=0.0.4=pyhcf101f3_0
  - annotated-types=0.6.0=py314h06a4308_1
  - anyio=4.10.0=py314h06a4308_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.4=h06a4308_0
  - certifi=2025.11.12=py314h06a4308_0
  - cffi=2.0.0=py314h4eded50_1
  - click=8.2.1=py314h06a4308_0
  - cryptography=46.0.3=py314h0a354b3_0
  - dnspython=2.4.2=py314h06a4308_0
  - email-validator=2.3.0=py314h06a4308_0
  - email_validator=2.3.0=hd3eb1b0_0
  - expat=2.7.3=h3385a95_0
  - fastapi=0.121.3=hf029e93_0
  - fastapi-cli=0.0.16=pyhcf101f3_1
  - fastapi-core=0.121.3=pyhcf101f3_0
  - h11=0.16.0=py314h06a4308_1
  - httpcore=1.0.9=py314h06a4308_0
  - httptools=0.7.1=py314h47b2149_0
  - httpx=0.28.1=py314h06a4308_1
  - idna=3.11=py314h06a4308_0
  - isodate=0.7.2=py314h06a4308_1
  - jinja2=3.1.6=py314h06a4308_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libmpdec=4.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.48.0=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - markdown-it-py=4.0.0=py314h06a4308_0
  - markupsafe=3.0.2=py314h5eee18b_0
  - mdurl=0.1.2=py314h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.3=pyh0d26453_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=2.12.3=py314h06a4308_1
  - pydantic-core=2.41.4=py314h498d7c9_0
  - pygments=2.19.2=py314h06a4308_0
  - pyparsing=3.2.0=py314h06a4308_0
  - python=3.14.0=h3fc5862_101_cp314
  - python-dotenv=1.1.0=py314h06a4308_0
  - python-multipart=0.0.20=py314h06a4308_0
  - python_abi=3.14=1_cp314
  - pyyaml=6.0.3=py314h591646f_0
  - rdflib=7.4.0=pyhcf101f3_0
  - readline=8.3=hc2a1206_0
  - rich=14.2.0=py314h06a4308_0
  - rich-toolkit=0.16.0=pyhcf101f3_0
  - shellingham=1.5.4=py314h06a4308_0
  - sniffio=1.3.0=py314h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - starlette=0.50.0=pyhfdc7a7d_0
  - tk=8.6.15=h54e0aa7_0
  - tomli=2.2.1=py314h06a4308_0
  - typer=0.17.4=py314h06a4308_0
  - typing-extensions=4.15.0=py314h06a4308_0
  - typing-inspection=0.4.2=py314h06a4308_0
  - typing_extensions=4.15.0=py314h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - uvicorn=0.38.0=pyh31011fe_0
  - uvicorn-standard=0.38.0=h31011fe_0
  - uvloop=0.22.1=py314h939ff40_1
  - watchfiles=1.1.1=py314ha5689aa_0
  - websockets=15.0.1=py314h5eee18b_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - pyoxigraph==0.5.2
prefix: /home/lasse/miniconda3/envs/conserFAIRy
